# Generated by Django 3.1.3 on 2020-11-24 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.TextField()),
                ('endDate', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('totalPrice', models.IntegerField()),
                ('src', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='endDate',
        ),
        migrations.AddField(
            model_name='events',
            name='startDate',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
