# Generated by Django 3.1.3 on 2020-11-26 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_auto_20201126_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryHelp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='donate',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Achievments_From_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('achive_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.achievment')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='category_help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.categoryhelp'),
        ),
    ]
