# Generated by Django 3.1.3 on 2020-11-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_auto_20201124_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='src',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='src',
        ),
        migrations.AddField(
            model_name='donate',
            name='img',
            field=models.ImageField(default='/Volonter/TestApp/Templates/hehe.jpg', upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='events',
            name='img',
            field=models.ImageField(default='/Volonter/TestApp/Templates/hehe.jpg', upload_to='upload/'),
        ),
        migrations.CreateModel(
            name='Donates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.donate')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.events')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.users')),
            ],
        ),
    ]
