# Generated by Django 3.1.3 on 2020-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_auto_20201126_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='UuidAndEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=200)),
                ('action', models.IntegerField()),
            ],
        ),
    ]
