# Generated by Django 3.1.3 on 2020-11-25 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestApp', '0003_auto_20201125_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='img',
            field=models.ImageField(default='static/hehe.jpg', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(default='static/hehe.jpg', upload_to='upload/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.profile'),
        ),
        migrations.AlterField(
            model_name='donates',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.profile'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
