# Generated by Django 3.1.3 on 2020-11-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_uuidandemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievments_from_user',
            old_name='achive_id',
            new_name='achive',
        ),
        migrations.RenameField(
            model_name='achievments_from_user',
            old_name='user_id',
            new_name='user',
        ),
    ]
