# Generated by Django 3.1.3 on 2020-11-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0005_auto_20201126_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievments_From_User',
        ),
    ]
