# Generated by Django 3.1.3 on 2020-11-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0006_delete_achievments_from_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievments_From_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('achive_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.achievment')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
